version: '3'
services:
  #Master Ansible
  master:
      build: master/
      working_dir: /root/playbooks
      volumes:
        - ${PWD}/playbooks:/root/playbooks
        - ${PWD}/config:/etc/ansible
      command: tail -f /dev/null
      #command: ansible-playbook /etc/ansible/install.yml
      networks:
         - challenge
      restart: always
  

  # Node1 
  node1:
      build: node/
      networks:
         - challenge
      restart: always
      ports:
        - "5601:5601"
      
  # Node2
  node2:
      build: node/
      networks:
          - challenge
      restart: always


  # Node3
  node3:
      build: node/
      networks:
          - challenge
      restart: always
      ports:
        - "80:80"

  # Test ENV
  node4:
      build: node/
      networks:
          - challenge
      restart: always
      ports:
        - "5602:5601"

  node5:
      build: node/
      networks:
          - challenge
      restart: always

  node6:
      build: node/
      networks:
          - challenge
      restart: always

networks:
    challenge:
        driver: bridge
