#installing Java on node1
- hosts: elastic
  gather_facts: yes

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - name: Install Java Runtime Environment
      become: yes
      apt:
       name: default-jre
       state: present

#installing elasticsearch on node1
- hosts: elastic
  gather_facts: no

  tasks:
    - name: Download Elastic Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-amd64.deb
        dest: /tmp

    - name: Install Elastic Deb Package
      become: yes
      apt:
        deb: /tmp/elasticsearch-7.8.1-amd64.deb

    - name: Update Elastic Config (IP Address to 0.0.0.0)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'network.host'
        line: 'network.host: 0.0.0.0'

    - name: Updating Elastic Config (Port Number)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'http.port'
        line: 'http.port: 9200'

    - name: Updating Elastic Config (Node Name)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#node.name: node-1'
        line: 'node.name: node-1'

    - name: Updating Elastic Config (Cluster Initial Master Nodes)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        line: 'cluster.initial_master_nodes: ["node-1"]'

    - name: Start ElasticSearch Service
      become: yes
      service:
        name: elasticsearch
        state: started

#intalling Kibana on node1
- hosts: elastic
  gather_facts: no

  tasks:
    - name: Download Kibana Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/kibana/kibana-7.8.1-amd64.deb
        dest: /tmp

    - name: Install Kibana Deb Package
      become: yes
      apt:
        deb: /tmp/kibana-7.8.1-amd64.deb

    - name: Update Kibana Config (IP Address)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.host'
        line: 'server.host: "0.0.0.0"'
    
    - name: Updating Kibana Port
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.port'
        line: 'server.port: 5601'

    - name: Update Kibana Config (Kibana URL)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'elasticsearch.hosts'
        line: 'elasticsearch.hosts: ["http://localhost:9200"]'

    - name: Start Kibana Service
      become: yes
      service:
        name: kibana
        state: started

#installing JAVA on node2
- hosts: logstash
  gather_facts: yes
  
  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - name: Install Java Runtime Environment
      become: yes
      apt:
       name: default-jre
       state: present

#installing logstash on node2
- hosts: logstash
  gather_facts: no

  tasks:
    - name: Download Logstash Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/logstash/logstash-7.8.1.deb
        dest: /tmp

    - name: Install Logstash Deb Package
      become: yes
      apt:
        deb: /tmp/logstash-7.8.1.deb

    - name: Create Logstash Pipeline File
      become: yes
      file:
         path: /etc/logstash/conf.d/main.conf
         state: touch

    - name: Add Logstash Pipeline Configuration
      become: yes
      blockinfile:
         path: /etc/logstash/conf.d/main.conf
         marker: ""
         block: |
           input {
             beats {
               port => 5044
             }
           }
           output {
             elasticsearch { hosts => ["node1:9200"]
             }
           }
    - name: creating logstash service
      command: /usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv 

    # Enable Logstash service
    - name: Start logstash Service
      become: yes
      service:
        name: logstash
        state: started

#installing nginx on web instance
- hosts: web
  tasks:
    - name: Install Nginx Latest Version
      apt: name=nginx state=latest
    
    - name: Starting nginx
      service:
          name: nginx
          state: started